### ISSUE TITLE
Add images to project

### ISSUE THREAD

**Issue by jjokah** [BuildForSDGCohort2/disposify#2]
- [x] Add favico

- [x] Get image for title

- [ ] Get other images and resources from https://tailwindcss.com/resources

**Comment by peace-stack** [comment]
Hello Johnson ,


I have attached some Trash can Favicons. Do well to download.

**Comment by jjokah** [comment]
Kk. Sure.
Thanks

**Comment by jjokah** [comment]
Add images to the home page and error pages.
