### ISSUE TITLE
Implement django cookiecutter deployment for heroku

### ISSUE THREAD

**Issue by jjokah** [BuildForSDGCohort2/disposify#4]
This should fix the error:
`heroku config:set DJANGO_SETTINGS_MODULE=config.settings.production`

Then I have to still follow this deployment documentation:
https://cookiecutter-django.readthedocs.io/en/latest/deployment-on-heroku.html

**Comment by JohnJohnsonOkah** [comment]
Successfully deployed to Heroku.

**Comment by jjokah** [comment]
Successfully deploy to Heroku.
